# Generated by Django 4.1.1 on 2022-10-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_category_managers_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='media/products'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(upload_to='media/aksiya'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video'),
        ),
    ]
